<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{   
    // Get the products count in cart
	public function getProductsCount($cart_id) {

        $em = $this->getEntityManager();

        $count = $em->createQueryBuilder()
                ->select('SUM(c.quantity)')
                ->from('AppBundle:CartProduct', 'c')
                ->where('c.cart = '.$cart_id)
                ->getQuery()->getSingleResult();

        return $count[1];
    }

    // Get total price of the order
    public function getTotalPrice($cart_id) {

        $em = $this->getEntityManager();

        // Price
        $price = 0;

        $prods = $em->createQueryBuilder()
                ->select('c')
                ->from('AppBundle:CartProduct', 'c')
                ->where('c.cart = '.$cart_id)
                ->getQuery()->getResult();

        foreach($prods as $prod) {
            $price += $prod->getPrice()*$prod->getQuantity();
        }

        return $price;
    }

    // Get all confirmed
    public function getConfirmedCarts() {
        $em = $this->getEntityManager();

        $carts = $em->createQueryBuilder()
                ->select('c')
                ->from('AppBundle:Cart', 'c')
                ->where('c.confirmed > 0')
                ->getQuery()->getResult();

       return $carts;
    }

    // Get all confirmed by user
    public function getUserConfirmedCarts($user) {
        $em = $this->getEntityManager();

        $carts = $em->createQueryBuilder()
                ->select('c')
                ->from('AppBundle:Cart', 'c')
                ->where('c.confirmed > 0')
                ->andWhere('c.user = '.$user->getId())
                ->getQuery()->getResult();

        if(count($carts) > 0 ){
            return $carts;
        } else {
            return false;
        }
        
    }

}
